name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test-addition-formula
      id: test-addition-formula
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 3
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-ADDITION-FORMULA_RESULTS: "${{steps.test-addition-formula.outputs.result}}"
      with:
        runners: test-addition-formula
